imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: services.yml }

parameters:
  locale: en

framework:
  #esi: ~
  translator: { fallbacks: [] }
  secret: '%secret%'
  router:
    resource: '%kernel.project_dir%/app/config/routing.yml'
    strict_requirements: ~
  form: ~
  csrf_protection: ~
  validation: { enable_annotations: true }
  #serializer: { enable_annotations: true }
  default_locale: '%locale%'
  trusted_hosts: ~
  session:
    handler_id: session.handler.native_file
    save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
  fragments: ~
  http_method_override: true
  assets: ~
  php_errors:
    log: true

# Twig Configuration
twig:
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  form_themes:
    - 'bootstrap_3_layout.html.twig'
  globals:
    export_excel_relative: '%export_excel_relative%'
    model_relative_path: '%model_relative_path%'
    car_files_relative_path: '%car_files_relative_path%'
    car_invoice_relative_path: '%car_invoice_relative_path%'

# Doctrine Configuration
doctrine:
  dbal:
    driver: pdo_mysql
    host: '%database_host%'
    port: '%database_port%'
    dbname: '%database_name%'
    user: '%database_user%'
    password: '%database_password%'
    charset: UTF8

  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
  transport: '%mailer_transport%'
  host: '%mailer_host%'
  username: '%mailer_user%'
  password: '%mailer_password%'
  spool: { type: memory }

sensio_framework_extra:
  router:
    annotations: false

doctrine_migrations:
  organize_migrations: BY_YEAR_AND_MONTH

monolog:
  channels:
    - 'car-update'
    - 'export'
    - 'dump'
    - 'convert'

  handlers:
    car-update:
      type: stream
      path: '%kernel.logs_dir%/%kernel.environment%.car-update.log'
      level: debug
      channels:
        - 'car-update'

    export:
      type: stream
      path: '%kernel.logs_dir%/%kernel.environment%.export.log'
      level: debug
      channels:
        - 'export'

    dump:
      type: stream
      path: '%kernel.logs_dir%/%kernel.environment%.dump.log'
      level: debug
      channels:
        - 'dump'

    convert:
      type: stream
      path: '%kernel.logs_dir%/%kernel.environment%.convert.log'
      level: debug
      channels:
        - 'convert'
